CREATE TABLE files(
	id INTEGER PRIMARY KEY,
	filename TEXT NOT NULL,
	last_seen_at DATETIME,
	orphaned_at DATETIME,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER files_updated_at
AFTER UPDATE ON files
FOR EACH ROW
BEGIN
    UPDATE files SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
